Patch/credentials refactor
CoSMoSoftware/unity-millicast-rts pull request #16
Opened 2023-02-10 20:28 UTC by soorin1990

2023-02-12 22:27 UTC, Yousif-CS commented on Runtime/McSubscriber.cs
> +                   credentials.subscribe_token.Length > 0;
subscriber token can be null or empty, not like the publisher token

2023-02-12 22:28 UTC, Yousif-CS commented on Samples~/Credentials.asset
> +  subscribe_token: 84d9602165583c55bd4e98747fc9fa6a8ea32436ec124c80f66222e94863770e
please remove the tokens from the assets

2023-02-12 22:28 UTC, Yousif-CS commented on Samples~/Credentials.asset
> +  publish_token: 2fdcd054c32632891f524bacd41911cb12a83f525f0128866548d7299ae22bc3
same here

2023-02-12 23:51 UTC, Yousif-CS requested changes
Some change requests

2023-02-13 00:33 UTC, Yousif-CS commented
can we also change the following: 

`CheckValidCredentials in McSubscriber` to: 
```
        private bool CheckValidCredentials(McCredentials credentials)
        {
            if (credentials == null) return false;

            return !string.IsNullOrEmpty(streamName) &&
                   !string.IsNullOrEmpty(credentials.subscribe_url) &&
                   !string.IsNullOrEmpty(credentials.accountId);
        }
```

and `CheckValidCredentials in McPublisher` to: 
```
    private bool CheckValidCredentials(McCredentials credentials)
    {
      if (credentials == null) return false;

      return !string.IsNullOrEmpty(streamName) &&
             !string.IsNullOrEmpty(credentials.publish_token) &&
             !string.IsNullOrEmpty(credentials.publish_url) &&
             !string.IsNullOrEmpty(credentials.accountId);
    }
```
We also now require the account ID to be provided to the publisher as is needed for the viewer url

2023-02-13 01:23 UTC, soorin1990 commented on Samples~/Credentials.asset
> +  publish_token: 2fdcd054c32632891f524bacd41911cb12a83f525f0128866548d7299ae22bc3
done

2023-02-13 01:23 UTC, soorin1990 commented on Samples~/Credentials.asset
> +  subscribe_token: 84d9602165583c55bd4e98747fc9fa6a8ea32436ec124c80f66222e94863770e
done

2023-02-13 01:23 UTC, soorin1990 commented on Runtime/McSubscriber.cs
> +                   credentials.subscribe_token.Length > 0;
done

2023-02-13 02:48 UTC, Yousif-CS approved these changes

2023-02-13 04:51 UTC, Yousif-CS approved these changes

2023-02-13 20:54 UTC, merged