Feature/video config
CoSMoSoftware/unity-millicast-rts pull request #7
Opened 2023-02-05 19:29 UTC by soorin1990

1. Refactored videoConfigurationExample.cs
2. Udated UI in VideoConfigurationExample scene
3. Added video quality configuration options in scriptable object as dropdowns

2023-02-05 22:34 UTC, Yousif-CS requested changes

2023-02-05 22:34 UTC, Yousif-CS commented on Samples~/VideoConfiguration/VideoConfigExample.cs
>    [SerializeField] private VideoConfiguration videoConfiguration;
We need to also have `VideoConfiguration` be a UI setting for the `MCPublisher` script as well. This way, we allow users to select their video configuration scriptable object directly through the `MCPublisher` in the inspector. We should keep the programatic API: `SetVideoConfig` as is, but use the scriptable object setting to set the video codec, resolution, frame-rate and bitrate  settings through `MCPublisher` UI.

2023-02-07 00:32 UTC, soorin1990 commented on Samples~/VideoConfiguration/VideoConfigExample.cs
>    [SerializeField] private VideoConfiguration videoConfiguration;
Added VideoConfiguration variable to McPublisher
priority will be given to UI, if data not available then it will fetch data from McPublisher and display the default values in UI

2023-02-07 04:46 UTC, Yousif-CS commented on Runtime/McPublisher.cs
> +  [SerializeField] private VideoConfiguration _videoSettings;
I think we can make videoConfiguration private and serializable without needing a public interface for changing it, don't you think? Because video configuration shouldn't be set dynamically at runtime, and only though the UI interface.

2023-02-07 05:04 UTC, Yousif-CS commented on Samples~/VideoConfiguration/VideoConfigExample.cs
>    [SerializeField] private VideoConfiguration videoConfiguration;
What is the difference between `videoConfiguration` and `videoSettings`?

2023-02-07 05:13 UTC, Yousif-CS requested changes
Aside from the comments, can we also make `VideoConfig` totally private, as that is not needed to be exposed to the UI (as we are using VideoConfiguration which is an SO), and the scripting API uses `SetVideoConfig`

2023-02-07 22:05 UTC, soorin1990 commented on Samples~/VideoConfiguration/VideoConfigExample.cs
>    [SerializeField] private VideoConfiguration videoConfiguration;
both are same, i have named it as videoSettings in McPublisher as there is videoConfig variable already present. To avoid confusion, i ll rename it to videoConfigData to represent it as videoConfig from so

2023-02-07 22:10 UTC, soorin1990 commented on Runtime/McPublisher.cs
> +  [SerializeField] private VideoConfiguration _videoSettings;
Yes, we can make it private. To give more flexibility to the user, I made it public so that the user can override the data in McPublisher script from VideoConfiguration example, in scenarios where user dont want to use McPublisher directly, instead wants to override the data using SO from VideoConfigurationExample and fetch the default data from this SO and populate them in UI.

2023-02-07 22:34 UTC, soorin1990 commented
->refactored code as per your comments 

-> removed flexibility to override video config data from other scripts on to McPublisher script. users can only access the videoConfig data from McPublisher but cannot override data. Changes to video streaming can be done using SetVideoConfig API method.

2023-02-08 01:00 UTC, Yousif-CS approved these changes

2023-02-08 01:01 UTC, merged